# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Statora < Formula
  desc "PHP version manager — manages PHP, Composer, and extensions per project."
  homepage "https://github.com/khauvannam/statora-cli"
  version "1.0.1"
  license "MIT"

  on_macos do
    url "https://github.com/khauvannam/statora-cli/releases/download/v1.0.1/statora_1.0.1_darwin_all.tar.gz"
    sha256 "1d7dbbfec8bb6c7d63af673c378f90da1b4c09589f569bac1b77fef562a35b6b"

    define_method(:install) do
      bin.install "statora"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/khauvannam/statora-cli/releases/download/v1.0.1/statora_1.0.1_linux_x86_64.tar.gz"
      sha256 "0431b3150ce652f76f5d67e32d6072c803c0591ebca8a1fe89dd5421a1d1f1db"
      define_method(:install) do
        bin.install "statora"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/khauvannam/statora-cli/releases/download/v1.0.1/statora_1.0.1_linux_arm64.tar.gz"
      sha256 "a97047336ae8a4690007d056013061fae3c0b3f0a40fe93baa5354430a58033e"
      define_method(:install) do
        bin.install "statora"
      end
    end
  end

  def caveats
    <<~EOS
      To use statora as a transparent php/composer shim, add symlinks:
        ln -sf $(brew --prefix)/bin/statora $(brew --prefix)/bin/php
        ln -sf $(brew --prefix)/bin/statora $(brew --prefix)/bin/composer
    EOS
  end

  test do
    system "#{bin}/statora", "--help"
  end
end
