# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Statora < Formula
  desc "PHP version manager — manages PHP, Composer, and extensions per project."
  homepage "https://github.com/khauvannam/statora-cli"
  version "1.0.3"
  license "MIT"

  on_macos do
    url "https://github.com/khauvannam/statora-cli/releases/download/v1.0.3/statora_1.0.3_darwin_all.tar.gz"
    sha256 "1392b8e6b2c7f27784c9d6bbe56bb6e5e86c3585b7ffa3d5b6f40133b02ce837"

    define_method(:install) do
      bin.install "statora"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/khauvannam/statora-cli/releases/download/v1.0.3/statora_1.0.3_linux_x86_64.tar.gz"
      sha256 "646d9894878516d579ed3d06d1eb67895ab03fc509dfc13df32c078954f843af"
      define_method(:install) do
        bin.install "statora"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/khauvannam/statora-cli/releases/download/v1.0.3/statora_1.0.3_linux_arm64.tar.gz"
      sha256 "8fe2f9ed31cc28655e21e79f57ef38792e97b283a67232c07b8cfebb0c3401f4"
      define_method(:install) do
        bin.install "statora"
      end
    end
  end

  def caveats
    <<~EOS
      To enable PHP version switching, add to your shell rc:
        zsh/bash:  eval "$(statora env)"
        fish:      statora env | source

      To uninstall, remove statora data first:
        rm -rf ~/.statora
      Then run: brew uninstall statora
    EOS
  end

  test do
    system "#{bin}/statora", "--help"
  end
end
