# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Statora < Formula
  desc "PHP version manager — manages PHP, Composer, and extensions per project."
  homepage "https://github.com/khauvannam/statora-cli"
  version "1.0.5"
  license "MIT"

  on_macos do
    url "https://github.com/khauvannam/statora-cli/releases/download/v1.0.5/statora_1.0.5_darwin_all.tar.gz"
    sha256 "f15dabec75c3001c74b027665afc1d02503bcd87edd8a550a9a12795f616824d"

    define_method(:install) do
      bin.install "statora"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/khauvannam/statora-cli/releases/download/v1.0.5/statora_1.0.5_linux_x86_64.tar.gz"
      sha256 "0be4aeaf75320f369874858bfa05bce9df1ba428d99543b111f34e3ccbcc67f6"
      define_method(:install) do
        bin.install "statora"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/khauvannam/statora-cli/releases/download/v1.0.5/statora_1.0.5_linux_arm64.tar.gz"
      sha256 "d54666a53cc97dabb5e8138888ccd38e50c0b10c0509e21c7233a4261cedb5f4"
      define_method(:install) do
        bin.install "statora"
      end
    end
  end

  def caveats
    <<~EOS
      To enable PHP version switching, add to your shell rc:
        zsh/bash:  eval "$(statora env)"
        fish:      statora env | source

      To uninstall, remove statora data first:
        rm -rf ~/.statora
      Then run: brew uninstall statora
    EOS
  end

  test do
    system "#{bin}/statora", "--help"
  end
end
